name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord via curl
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \":rocket: Push by ${{ github.actor }} to \`${{ github.repository }}\`\nCommit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \
            $DISCORD_WEBHOOK