name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: tsickert/discord-webhook@v5
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            🚀 Push detected by ${{ github.actor }} on ${{ github.repository }}
            🔗 [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})